config/routes.rb
Ptm::Application.routes.draw do |map|
  get "tasks/index"
  match "tasks/:id/delete", :to => "tasks#destroy", :as => :delete_task
  match "tasks/:id/finish", :to => "tasks#finish", :as => :finish_task
  match "tasks/finished", :to => "tasks#finished", :as => :finished_tasks

  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base

  scope :finished, where("tasks.finished IS NOT NULL").order("finished DESC")

  scope :unfinished, where("tasks.finished IS NULL")

  def finished?
    finished != nil
  end

  def finish
    update_attributes(:finished => Time.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.unfinished
  end

  def finished
    @tasks = Task.finished
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create!(params[:task])
    flash[:notice] = "New task created."
    redirect_to tasks_path
  end

  def destroy
    task = Task.find(params[:id])
    task.delete
    flash[:notice] = "Task deleted."
    redirect_to tasks_path
  end

  def finish
    task = Task.find(params[:id])
    task.finish
    flash[:notice] = "Task finished."
    redirect_to tasks_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ptm</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_task.html.erb
<div class="task">
  <h2><%= task.title %></h2>
  <p><%= task.comment %></p>
  <p>
    <% if task.finished? %>
      Finished: <%= task.finished %>
    <% else %>
      <%= link_to "Finish", finish_task_url(task) %>
    <% end %>
    | <%= link_to "Delete", delete_task_url(task) %>
  </p>
</div>

app/views/tasks/finished.html.erb
<%= flash[:notice] %>
<h1>Tasks</h1>
<% for task in @tasks %>
  <%= render :partial => "task", :object => task %>
<% end %>

app/views/tasks/index.html.erb
<%= flash[:notice] %>
<h1>Tasks</h1>
<% for task in @tasks %>
  <%= render :partial => "task", :object => task %>
<% end %>
<%= link_to "New Task", new_task_path %>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </p>
  <p class="button"><%= f.submit "Create" %></p>
<% end %>